agora_game_augustus_create:
  path: /create/{gameId}
  defaults: { _controller: AugustusBundle:Game:createRoom }

agora_game_augustus_join:
  path: /join/{gameId}
  defaults: { _controller: AugustusBundle:Game:joinRoom }

agora_game_augustus_index:
  path: /index/{gameId}
  defaults: { _controller: AugustusBundle:Game:index }

