services:
    agora_game.augustus:
        class: AGORA\Game\AugustusBundle\Service\AugustusService
        arguments: ["@doctrine.orm.entity_manager"]

    agora_game.augustusController:
        class: AGORA\Game\AugustusBundle\Controller\GameController
