agora_game_create_sqp:
    path: /game/create/sqp
    defaults: { _controller: AGORAGameSQPBundle:Default:createLobby }

agora_game_join_sqp:
    path: /game/join/sqp/{idGame}
    defaults: { _controller: AGORAGameSQPBundle:Default:joinLobby, idGame: "1" }

agora_game_delete_sqp:
    path: /game/delete/sqp/{idGame}
    defaults: { _controller: AGORAGameSQPBundle:Default:delete, idGame: "1" }